# Generated by Django 4.2.6 on 2023-10-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_level_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='picture',
            field=models.ImageField(upload_to='SUBJECTS'),
        ),
    ]
