# Generated by Django 4.2.6 on 2023-10-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_lesson_uuid_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fiche_presentation',
            field=models.FileField(blank=True, null=True, upload_to='FICHE_PRESENTATION', verbose_name='FICHE_PRESENTATION'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='fichier_pdf',
            field=models.FileField(blank=True, null=True, upload_to='FICHE_PDF', verbose_name='FICHE_PDF'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='VIDEO', verbose_name='VIDEO'),
        ),
    ]
