# Generated by Django 4.2.6 on 2023-10-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_alter_lesson_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
